//! Customer-facing route metadata registry.

use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct RouteMetadata {
    pub path: &'static str,
    pub method: &'static str,
    pub category: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub docs_href: &'static str,
    pub auth_mode: &'static str,
    pub dashboard_visible: bool,
    pub playground_supported: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub async_variant: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub polling_route: Option<&'static str>,
    pub sample_key: &'static str,
}

/// Returns the full list of customer-facing route metadata.
pub fn customer_route_registry() -> Vec<RouteMetadata> {
    vec![
        RouteMetadata {
            path: "/v1/search",
            method: "POST",
            category: "core",
            label: "Search",
            description: "Federated search across retrieval backends with ranking and citations.",
            docs_href: "https://docs.fetchium.com/api/search",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: None,
            sample_key: "search",
        },
        RouteMetadata {
            path: "/v1/scrape",
            method: "POST",
            category: "core",
            label: "Scrape",
            description: "Fetch and extract a page with query-aware structured content output.",
            docs_href: "https://docs.fetchium.com/api/scrape",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: None,
            sample_key: "scrape",
        },
        RouteMetadata {
            path: "/v1/fetch",
            method: "POST",
            category: "core",
            label: "Fetch",
            description: "Extract clean content from a single URL with a token budget.",
            docs_href: "https://docs.fetchium.com/api/scrape",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: None,
            sample_key: "fetch",
        },
        RouteMetadata {
            path: "/v1/estimate",
            method: "POST",
            category: "core",
            label: "Estimate",
            description: "Preview extraction cost and token budget before fetching.",
            docs_href: "https://docs.fetchium.com/api/estimate",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: None,
            sample_key: "estimate",
        },
        RouteMetadata {
            path: "/v1/research",
            method: "POST",
            category: "research",
            label: "Research",
            description: "Multi-step research synthesis with source-backed output.",
            docs_href: "https://docs.fetchium.com/api/research",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/research/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "research",
        },
        RouteMetadata {
            path: "/v1/research/jobs",
            method: "POST",
            category: "jobs",
            label: "Research Jobs",
            description: "Submit a research job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "research",
        },
        RouteMetadata {
            path: "/v1/youtube/search",
            method: "POST",
            category: "media",
            label: "YouTube Search",
            description: "Search YouTube content with Fetchium's media pipeline.",
            docs_href: "https://docs.fetchium.com/api/youtube",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/youtube/search/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "youtube_search",
        },
        RouteMetadata {
            path: "/v1/youtube/search/jobs",
            method: "POST",
            category: "jobs",
            label: "YouTube Search Jobs",
            description: "Submit a YouTube search job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "youtube_search",
        },
        RouteMetadata {
            path: "/v1/youtube/analyze",
            method: "POST",
            category: "media",
            label: "YouTube Analyze",
            description: "Analyze a single video URL for metadata and transcript intelligence.",
            docs_href: "https://docs.fetchium.com/api/youtube",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/youtube/analyze/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "youtube_analyze",
        },
        RouteMetadata {
            path: "/v1/youtube/analyze/jobs",
            method: "POST",
            category: "jobs",
            label: "YouTube Analyze Jobs",
            description: "Submit a YouTube analysis job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "youtube_analyze",
        },
        RouteMetadata {
            path: "/v1/social/research",
            method: "POST",
            category: "social",
            label: "Social Research",
            description: "Cross-platform social research across the supported social sources.",
            docs_href: "https://docs.fetchium.com/api/social",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/social/research/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "social_research",
        },
        RouteMetadata {
            path: "/v1/social/research/jobs",
            method: "POST",
            category: "jobs",
            label: "Social Research Jobs",
            description: "Submit a social research job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "social_research",
        },
        RouteMetadata {
            path: "/v1/social/reddit",
            method: "POST",
            category: "social",
            label: "Reddit Social",
            description: "Query social signals from Reddit through the Fetchium API.",
            docs_href: "https://docs.fetchium.com/api/social",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/social/reddit/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "reddit",
        },
        RouteMetadata {
            path: "/v1/social/reddit/jobs",
            method: "POST",
            category: "jobs",
            label: "Reddit Jobs",
            description: "Submit a Reddit search job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "reddit",
        },
        RouteMetadata {
            path: "/v1/social/hackernews",
            method: "POST",
            category: "social",
            label: "Hacker News Social",
            description: "Query discussion and signal data from Hacker News.",
            docs_href: "https://docs.fetchium.com/api/social",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: Some("/v1/social/hackernews/jobs"),
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "hackernews",
        },
        RouteMetadata {
            path: "/v1/social/hackernews/jobs",
            method: "POST",
            category: "jobs",
            label: "Hacker News Jobs",
            description: "Submit a Hacker News search job for asynchronous execution.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: Some("/v1/jobs/:id"),
            sample_key: "hackernews",
        },
        RouteMetadata {
            path: "/v1/jobs/:id",
            method: "GET",
            category: "jobs",
            label: "Job Status",
            description: "Poll a previously submitted async job by job ID.",
            docs_href: "https://docs.fetchium.com/api/async-jobs",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: true,
            async_variant: None,
            polling_route: None,
            sample_key: "job_status",
        },
        RouteMetadata {
            path: "/v1/usage",
            method: "GET",
            category: "utility",
            label: "Usage",
            description: "Inspect request quota, plan limits, and current key usage.",
            docs_href: "https://docs.fetchium.com/api/usage",
            auth_mode: "bearer_key",
            dashboard_visible: true,
            playground_supported: false,
            async_variant: None,
            polling_route: None,
            sample_key: "usage",
        },
        RouteMetadata {
            path: "/v1/health",
            method: "GET",
            category: "utility",
            label: "Health",
            description: "Check API health and availability.",
            docs_href: "https://docs.fetchium.com/api/health",
            auth_mode: "public",
            dashboard_visible: true,
            playground_supported: false,
            async_variant: None,
            polling_route: None,
            sample_key: "health",
        },
    ]
}
